# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce10c902b424c0d7951f70fdb8ec9d6a255bd3278e46adfe2bee507b87319a1eed2670b647b9460182e70a109e980c9561e82b2946fb88cfd394fe06345f66dd

test:
  secret_key_base: 2f04245d632d1697a4be60bf7e12edd684f4bff160e5b45fbd8e72e511d056a250bcb8ac662eecff6fad907bbcbbc8934977874d279084c4dde3b9e79151c2c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
